package:
  name: crossplane-provider-gcp
  version: "2.0.0"
  epoch: 1
  description: Official GCP Provider for Crossplane by Upbound
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 16
    memory: 32Gi
  dependencies:
    runtime:
      - terraform-provider-google

environment:
  contents:
    packages:
      - build-base
      - busybox
      - crossplane-crank
      - gzip
      - jq
      - kustomize
  environment:
    CGO_ENABLED: 0

vars:
  marketplace.version: 1.14.1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/crossplane-contrib/provider-upjet-gcp
      tag: v${{package.version}}
      expected-commit: 31b17547a6cb0899f95914c8cc9e3e8ef6cfcd95
      recurse-submodules: true

data:
  - name: packages
    items:
      config: provider-family-gcp
      compute: provider-gcp-compute
      storage: provider-gcp-storage
      pubsub: provider-gcp-pubsub
      kms: provider-gcp-kms
      dns: provider-gcp-dns
      container: provider-gcp-container
      cloudplatform: provider-gcp-cloudplatform

subpackages:
  - name: crossplane-${{range.value}}
    range: packages
    description: "Crossplane GCP ${{range.key}} provider"
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/provider/${{range.key}}
          output: ${{range.value}}
          ldflags: |
            -X github.com/crossplane-contrib/provider-upjet-gcp/internal/version.Version=v${{package.version}}
      - runs: |
          crank xpkg extract ghcr.io/crossplane-contrib/${{range.value}}:v${{package.version}}
          gunzip out.gz -c > ${{targets.contextdir}}/package.yaml
    test:
      environment:
        contents:
          packages:
            - openssl
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/kwok/cluster
        - name: Running the operator
          uses: test/daemon-check-output
          with:
            setup: |
              mkdir -p /tls/server
              openssl req -x509 -newkey rsa:2048 -keyout /tls/server/tls.key \
                -out /tls/server/tls.crt -days 1 -nodes -subj "/CN=test"
              chmod 600 /tls/server/tls.key
              chmod 644 /tls/server/tls.crt
            start: |
              ${{range.value}}
            timeout: 30
            expected_output: |
              "logger":"provider-gcp"
              EnableBetaManagementPolicies
            post: |
              echo "Provider started with expected behavior"

  - name: crossplane-${{range.value}}-compat
    range: packages
    description: Provides ${{range.value}} at /usr/local/bin/provider
    dependencies:
      runtime:
        - crossplane-${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/local/bin
          ln -s /usr/bin/${{range.value}} ${{targets.contextdir}}/usr/local/bin/provider
    test:
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: true

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: crossplane-contrib/provider-upjet-gcp
    strip-prefix: v
