package:
  name: dask-kubernetes
  version: "2025.4.3"
  epoch: 0
  description: "Native Kubernetes integration for Dask"
  copyright:
    - license: "BSD-3-Clause"
  options:
    no-depends: true
  dependencies:
    provider-priority: 0

vars:
  pypi-package: dask-kubernetes

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  environment:
    SOURCE_DATE_EPOCH: "315532900"
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - py3-supported-hatch
      - py3-supported-hatch-vcs
      - py3-supported-pip
      - py3-supported-python
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dask/dask-kubernetes.git
      tag: ${{package.version}}
      expected-commit: 547c911efc58fa003d4cb8d49fcd58a7536fa7e7

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: "Dask Kubernetes built for python${{range.key}}"
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
        - ${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - runs: pip${{range.key}} install --prefix=/usr "--root=${{targets.contextdir}}" dask distributed kopf kr8s kubernetes kubernetes-asyncio pykube-ng rich
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

update:
  enabled: true
  manual: false
  github:
    identifier: dask/dask-kubernetes
