package:
  name: luarocks
  version: 3.11.1
  epoch: 0
  description: "Package manager for Lua modules"
  copyright:
    - license: MIT
  options:
    no-depends: true
  dependencies:
    runtime:
      - curl
      - gcc
      - git
      - luajit

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - luajit-dev
      - openssl-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/luarocks/luarocks
      tag: v${{package.version}}
      expected-commit: fa2736e7c68094710643577b0153dac72ce4bcdc

  - runs: ./configure --prefix=/usr --with-lua=/usr

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: true
  github:
    identifier: luarocks/luarocks
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - luajit-dev
        - glibc-dev
  pipeline:
    - runs: |
        luarocks --version
        luarocks install luasocket
