package:
  name: py3-tiktoken
  version: 0.9.0
  epoch: 0
  description: A fast BPE tokeniser for use with OpenAI's models.
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: tiktoken
  import: tiktoken

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - build-base
      - gcc
      - py3-supported-build-base
      - rust

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e35ab0915e37b919946b70947f1d0854196cb72c
      repository: https://github.com/openai/tiktoken
      tag: ${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - name: Python Build
        uses: python/build-wheel
      - uses: strip

update:
  enabled: true
  github:
    identifier: openai/tiktoken

test:
  pipeline:
    - uses: test/tw/header-check
      with:
        files: |
          doctest/doctest.h
          doctest/extensions/doctest_util.h
