package:
  name: rancher-security-scan-0.6
  description: Tests Kubernetes clusters for adherence to security best practices using kube-bench
  epoch: 0
  version: 0.6.1
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher-security-scan=${{package.full-version}}
    runtime:
      - curl
      - diffutils
      - findutils
      - gawk
      - gnutar
      - gzip
      - jq
      - procps
      - systemd

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/security-scan.git
      expected-commit: 84f88f7bf70923788959a49edf0c421ff2dcd584
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        github.com/go-viper/mapstructure/v2@v2.3.0
      modroot: .

  - uses: go/build
    with:
      ldflags: -X main.version=v${{package.version}}
      packages: ./cmd/kb-summarizer/
      output: kb-summarizer

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      install -Dm755 ./package/run.sh ${{targets.destdir}}/usr/bin/
      install -Dm755 ./package/run_sonobuoy_plugin.sh ${{targets.destdir}}/usr/bin/
      install -Dm755 ./package/helper_scripts/* ${{targets.destdir}}/usr/bin/

test:
  pipeline:
    - name: version and command test
      runs: |
        kb-summarizer --help

update:
  enabled: true
  ignore-regex-patterns:
    - .*-rc.*
  github:
    identifier: rancher/security-scan
    use-tag: true
    strip-prefix: v
    tag-filter: v0.6
